Add cart view
travisbartholome/cosc4351-final-project pull request #16
Opened 2020-04-20 01:55 UTC by duynle134679

2020-04-20 02:00 UTC, MohammadQHabib requested changes

2020-04-20 02:00 UTC, MohammadQHabib commented on views/cart.ejs
> +									<span class="glyphicon glyphicon-trash" onclick="deleteCartItem(<%= item.id %>)"> </span>
the glyphicons are not compatible with bootstrap 4, we should change them to font awesome 5.7 equivalents

2020-04-20 02:31 UTC, travisbartholome requested changes
A few things, mostly small changes. I think if you do these it should at least render.

We have API endpoints already for adding and removing a single item from the cart, which you can use here (I was picturing like a `-` and `+` button for each cart item). We could also have another button that just deletes a specific cart entry entirely (probably a good thing to have tbh, I hadn't thought about it), in which case we'd use something similar to the backend/db code you wrote. But I think if we do that we should still move the endpoint into the api router with the rest of the api endpoints, rather than putting it in app.js, and it should be a POST endpoint that looks similar to the add and remove endpoints (maybe hook it up to `/api/cart/delete`).

2020-04-20 02:31 UTC, travisbartholome commented on views/cart.ejs
> +					<% cart_items.forEach(function(item){ %>
Should be cart.products.forEach

2020-04-20 02:31 UTC, travisbartholome commented on app.js
> +// app.get('/delete', async (req, res) => {
Delete this if unused (it should be unused, since we already have an api endpoint to remove an item from the cart).

2020-04-20 02:31 UTC, travisbartholome commented on db/dbFunctions.js
> +const deleteCart = (id) => {
I don't think we need this function either, we already have `removeItemFromCart` above. Plus we have no way of knowing the ID for a particular cart item row on the frontend, and I don't think that should change.

2020-04-20 02:31 UTC, travisbartholome commented on views/cart.ejs
> +      window.location.href='/delete?id=' + id;
Look at the way we've implemented the add to cart buttons in browse.ejs to get a better idea of what this function should look like (it should basically be the same, but POST to `/api/cart/remove` instead of `/api/cart/add`). For now you can just console.log the result to see if it's working (or something like that).

2020-04-20 02:31 UTC, travisbartholome commented on views/cart.ejs
> +							<h4 class="text-right">Total <strong>$50.00</strong></h4>
Use `<%= cart.total %>` instead of hardcoding to $50.00.

2020-04-20 02:31 UTC, travisbartholome commented on views/cart.ejs
> +							<h4 class="product-name"><strong><%= item['product.name'] %></strong></h4><h4><small>Product description</small></h4>
Use `item.name` instead of `item['product.name']`

2020-04-20 02:31 UTC, travisbartholome commented on views/cart.ejs
> +						<div class="col-xs-2"><img class="product-image" style="width:100px; height:100px" src="/static/images/<%= item['product.image'] %>">
Use `item.image` instead of `item['product.image']`

2020-04-20 02:31 UTC, travisbartholome commented on app.js
> +
Not sure why this extra newline is here

2020-04-20 05:25 UTC, travisbartholome requested changes
Other than the database config and the icon stuff, I think the code looks good. Can you comment with a screenshot of the cart page, for reference?

Also when you make changes, you can just make a new commit and push it normally - you don't have to force-push (although I guess it doesn't really matter that much).

2020-04-20 05:25 UTC, travisbartholome commented on db/db.js
> +        // dialectOptions: {
If you're having to comment these out to get your local version to work, something is wrong with your .env file. Do you have it configured with the db credentials that are in the Google doc? I don't think we can merge with these commented out.

2020-04-20 05:25 UTC, travisbartholome commented on views/cart.ejs
> +							<button type="button" class="btn btn-success btn-block" onclick="checkout()">
If you want, I think you can change this button to an `<a href="/checkout" class="btn btn-success btn-block">Checkout</a>`, and then you won't have to manipulate `window.location.href` manually (and you also won't need the checkout() function). I'm pretty sure the styling will work the same but I might be wrong, in which case just leave it I guess.

2020-04-20 05:25 UTC, travisbartholome commented on views/cart.ejs
> +								<button type="button" class="btn btn-primary btn-sm btn-block" onclick="continueShopping()">
I made a comment down below about the checkout button - similar thing applies here, I think. Would be easier (if the styles work) to change the button element to an `<a>`, href="/", keep the same classes, drop the onclick method. Again, if the style doesn't work that way, you can just leave it.

2020-04-20 05:25 UTC, travisbartholome commented on views/head.ejs
> +<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigi
I think changing this will break Mohammad's other UI code, so we should use bootstrap 4.0.0 (he mentioned it earlier but didn't comment on this line).

2020-04-20 05:25 UTC, travisbartholome commented on views/cart.ejs
> +									<span class="glyphicon glyphicon-trash" onclick="deleteCartItem(<%= item.id %>)"> </span>
For reference: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Basically instead of using the glyphicon classes you'll have `<span class="fas fa-trash" onclick="deleteCartItem(<%= item.id %>)"></span>`

2020-04-20 05:27 UTC, travisbartholome commented on views/head.ejs
> +<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigi
@MohammadQHabib confirm?

2020-04-20 05:30 UTC, MohammadQHabib commented on views/head.ejs
> +<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigi
Yea we need to use 4.0.0 or my navbar and the checkout page, icons will not work

2020-04-20 05:56 UTC, duynle134679 commented on views/head.ejs
> +<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigi
yeah. I'll update the css and if it's not working, I'll just look for another template online using 4.0 version

2020-04-20 05:57 UTC, duynle134679 commented on db/db.js
> +        // dialectOptions: {
> Other than the database config and the icon stuff, I think the code looks good. Can you comment with a screenshot of the cart page, for reference?
> 
> Also when you make changes, you can just make a new commit and push it normally - you don't have to force-push (although I guess it doesn't really matter that much).

I'll update the screenshot after I'm done with the styling Travis

2020-04-20 06:42 UTC, duynle134679 commented
![cart_page](https://user-images.githubusercontent.com/57854332/79721537-1ebc6080-82a8-11ea-85dc-bab0bbad8927.png)

2020-04-20 17:09 UTC, MohammadQHabib commented
It looks you have an option for a promo code, I think we could just take that out at this point, it would be better in the checkout view if we add it at all but i don't think its that necessary. Other wise I like the general view, there are a few button spacing and color scheme mismatches but I can take care of that

2020-04-21 14:27 UTC, duynle134679 commented
![cart_view](https://user-images.githubusercontent.com/57854332/79877747-40097380-83b2-11ea-9226-c050c0c42ad6.jpg)

2020-04-21 14:53 UTC, travisbartholome approved these changes

2020-04-21 14:53 UTC, merged